const SR_COOL: string[] = [
    "2nd Hammer",
    "Afanc",
    "Agatha",
    "Agreas",
    "Akashic Record",
    "Alecto",
    "Alien",
    "Aludra",
    "Amefurashi",
    "Amore Tenderness",
    "Angler",
    "Anne Bonny",
    "Aqua",
    "Arche",
    "Arion",
    "Artemis",
    "Asherah",
    "Assault Reporter",
    "Atropos",
    "Aurora",
    "Azure Dragon",
    "Baena",
    "Barbatos",
    "Bestia",
    "Beulah",
    "Brain Crusher",
    "Brush Master",
    "Capella",
    "Cetus",
    "Chaucer",
    "Chess",
    "Chrollo",
    "Clarice",
    "Consort Wu",
    "Cool Fairy",
    "Cora",
    "Coucke",
    "Cowardly Bellona",
    "Crystal Koz",
    "Cthulhu",
    "Cyberwizard",
    "Cyborg",
    "Cyborg (Old)",
    "Dantalion",
    "Daredevil",
    "Delice",
    "Demon Summoner",
    "Despoina",
    "Divine Eos",
    "DIY Ninja",
    "Doll Princess",
    "Dorothy",
    "Dragon Princess",
    "Empress",
    "Empress (Old)",
    "Eva",
    "Fallen Samurai",
    "Fermata",
    "Festival Forneus",
    "Finette",
    "Flower Fairy",
    "Freshman Seven",
    "Frigg",
    "Frosty",
    "Gardener",
    "Gerhilde",
    "Gleipnir",
    "Gloriana",
    "Gold Rush",
    "Goldust",
    "Grumpy Princess",
    "Gungnir",
    "Halloween Astraea",
    "Harihara",
    "Headmaster",
    "Hermes",
    "Hervor",
    "Hijack",
    "Himiko",
    "Honorius",
    "Huwawa",
    "Infeliz",
    "Jaune Brillant",
    "Jinn",
    "Kagura",
    "Kayatsuhime",
    "Kikyo",
    "Kototowa",
    "Koz",
    "Lagrasse",
    "Laperm",
    "Larxsus",
    "Leviathan Ex",
    "Librarian",
    "Lina",
    "Lira",
    "Lisay",
    "Loche",
    "Love Succubus",
    "Luana",
    "Luce",
    "Mahadevi",
    "Mahjong Champ",
    "Maid Droid",
    "Manager",
    "Mani",
    "Matrix",
    "Maxwell",
    "Maya",
    "Mega Mover",
    "Melle",
    "Melody Timi",
    "Melty",
    "Mithrin",
    "Momiji",
    "Monochrome",
    "Morgiana",
    "Murakumo",
    "Mutsuki",
    "Nakisawame",
    "Nemesis",
    "Neptune",
    "Nonon",
    "Nott",
    "Nuwa",
    "Ochre",
    "Odysseus",
    "Oomin",
    "Organo-Mechanic",
    "Orihime",
    "Orlaya Mummy",
    "Ortlinde",
    "Paloma",
    "Paulina",
    "Pemphredo",
    "Petitrite",
    "Phanuel",
    "Phillis",
    "Philosopher",
    "Pit Mechanic",
    "Plantain Fan",
    "Poli'Ahu",
    "Princess Kaguya",
    "Prinny",
    "Prismatic Master",
    "Protector Nonon",
    "Prydwen",
    "Queen of Pirates",
    "Race Queen",
    "Reverie",
    "Sacred Sol",
    "Saketoke",
    "Sandalphon",
    "Sandy",
    "Sania",
    "Scarlet Hades",
    "Scue",
    "Seashell",
    "Seducir",
    "Sekhmet",
    "Shelly",
    "Shennong",
    "Sigrun",
    "Sinbad",
    "Skadi",
    "Sky Knight Arche",
    "Sky Navigator",
    "Snake Disciple",
    "Snow Baldr",
    "Snow Demon",
    "Snowman MK II",
    "Soleil",
    "Solomon",
    "Sonic Swordmaster",
    "Soul Conductor",
    "Soul Dowser",
    "Spade",
    "Strategist",
    "Strategist (Old)",
    "Stylist",
    "Sukis",
    "Super Chimry (Cool)",
    "Tenderness",
    "Teyr",
    "Thermae",
    "Theseus",
    "Thunderbolt",
    "Thuries",
    "Tiger Hunter",
    "Timi",
    "Titan",
    "Tone Of Rainbows",
    "Tovare",
    "Toyokumono",
    "True Lira",
    "Tyrano",
    "Tzitzimitl",
    "Ukanomitama",
    "Umbrella Phantom",
    "Urcaguary",
    "Urcaguary Ex",
    "Vasariah",
    "Vassago",
    "Vermelho",
    "Warlord",
    "Whale",
    "White Christmas",
    "White Night",
    "Winemaker",
    "Wisp",
    "Wreath",
    "Wuxia",
    "Xueren",
    "Yama",
    "Yeti",
    "Yuli",
    "Zahra",
    "Zephyrus",
    "Zombina",
    "Zver",
]

const SR_DARK: string[] = ["3rd Hammer",
    "Adonis",
    "Adroit Agreta",
    "Amath Haq",
    "Ambrosi",
    "Amfor",
    "Angra Mainyu",
    "Anya",
    "Applause",
    "Apprentice Emilie",
    "Asmodeus",
    "Asta",
    "Astaroth",
    "Azazel",
    "Balam",
    "Balor",
    "Beelzebub",
    "Belial",
    "Belphegor",
    "Bianca",
    "Biblio",
    "Bicorn",
    "Black Tortoise",
    "Bona",
    "Bonita",
    "Brioche",
    "Brule",
    "Bunny Misa",
    "Burglar",
    "Camilla",
    "Candy",
    "Cao Cao",
    "Caravan Jamie",
    "Catagion",
    "Champion",
    "Chandra",
    "Chang'E",
    "Chaos",
    "Charlemagne",
    "Chio",
    "Chocodevil",
    "Cirque du Luna",
    "Claudius",
    "Comfy Cat",
    "Cornutus",
    "Corvus",
    "Count Down",
    "Court Lady Anya",
    "Cpt. Bianca",
    "Croissant",
    "Damien",
    "Dark Alice",
    "Dark Fairy",
    "Dark Santa",
    "Data Scanner",
    "Decarabia",
    "Demon Lord",
    "Diana",
    "Doris",
    "Durandal",
    "Eleusis",
    "Elisabeth",
    "Erakis",
    "Eucharis",
    "Evelyne",
    "Farris",
    "Fennec",
    "Flu",
    "Follower Ketu",
    "Forneus",
    "Freischutz",
    "Fuga",
    "Fukori",
    "Gaap",
    "Giallo",
    "Glasya",
    "Graveyard Queen",
    "Greta",
    "Gretel",
    "Guardian Relena",
    "Hades",
    "Halloween Gem",
    "Halloween Sherry",
    "Hammock Babe",
    "Hecate",
    "Hell's Kitchen",
    "High Succubus",
    "High Vampire",
    "Hiruko",
    "Holy Crown",
    "Hot Spring Warabi",
    "Huang Gai",
    "Hypnos",
    "Inadama",
    "Infernal Hades",
    "Izanami",
    "Jack-O'-Sisters",
    "Jade",
    "Jingle Bell",
    "Joker",
    "Joker (Cane)",
    "Joker (Sickle)",
    "Jubilee Hostess",
    "Karin",
    "Keanos",
    "Kendama",
    "Keymaker",
    "Kotka",
    "Lakka",
    "Laranza",
    "Le Repas",
    "Leviathan",
    "Lich",
    "Lil' Vampire",
    "Lilim",
    "Lolli",
    "Lost Fairy",
    "Love Sniper",
    "Lovely",
    "Lu Bu",
    "Lucifer",
    "Lum Lum",
    "Lynx",
    "Mai Waifu",
    "Maia",
    "Mammon",
    "Marcia",
    "Mascotte",
    "Matcha",
    "Mephistopheles",
    "Merlin",
    "Mikli",
    "Miliann",
    "Nadia",
    "Nerthus",
    "Nightingale",
    "Nightmare",
    "Nyx",
    "Pandora",
    "Poet Amath Haq",
    "Polar Night",
    "Pollux",
    "Pretty Kitty",
    "Producer",
    "Queen Succubus",
    "Quinty",
    "Rambha",
    "Randgrith",
    "Rathgrith",
    "Red Girl",
    "Red String",
    "Resistance",
    "Rientes",
    "Rikayu in Chains",
    "Rimtas",
    "Ripple",
    "Roro",
    "Rossa",
    "Ruel",
    "Ruru",
    "Sandcastle Girl",
    "Sanja",
    "Satan",
    "Sazanami",
    "School Spirit",
    "Secret Wind Ninja",
    "Semiramis",
    "Shark",
    "Shingen",
    "Slime Guardian",
    "Snow White",
    "Sorbet",
    "Soror",
    "Star Erakis",
    "Subleader One",
    "Super Chimry",
    "Super Chimry (Dark)",
    "Surtr",
    "Susa-No-O",
    "Sylphis",
    "Sylvio",
    "Syrop",
    "Tagirihime",
    "Taishi Ci",
    "Takamine",
    "Tiel",
    "Tino",
    "Toilet Ghost",
    "Tolette",
    "Trident",
    "Uplala",
    "Vallee",
    "Vampire",
    "Vampire Slayer",
    "Vector",
    "Vermillion",
    "Veronica",
    "Virus Killer",
    "Vrykolakas",
    "Watz",
    "Weaponsmith",
    "White Dragon Horse",
    "Wind Ninja",
    "Yakshini",
    "Yuki Onna",
    "Yulan",
    "Yuu",
    "Zurvan"]

const SR_LIGHT = [
    "Acupuncturist",
    "Aero",
    "Aladdin",
    "Alnair",
    "Alpheratz",
    "Amadeus",
    "Amber",
    "Amenohoakari",
    "Amethyst",
    "Anahita",
    "Ancile",
    "Aphrodite",
    "Apollo",
    "Archangel",
    "Arianrhod",
    "Arum",
    "Asclepius",
    "Ash",
    "Asphodelus",
    "Astraea",
    "Athena",
    "Auxo",
    "Backstage Pixie",
    "Bastia",
    "Batur",
    "Beer Babe",
    "Bertina",
    "Blazing Muspell",
    "Blossom Princess",
    "Bookmarker",
    "Bunnikins",
    "Byakuya",
    "Caravan Muffin",
    "Card Collector",
    "Cardina",
    "Castor",
    "Cat's Cradle",
    "Catherina",
    "Celara",
    "Celestial Hades",
    "Chen Gong",
    "Chronos",
    "Chrysocolla",
    "Cochineal",
    "Cocoa",
    "Count Up",
    "Course Worker",
    "Dinosaur",
    "Dr. Feelgood",
    "Durga",
    "Effole",
    "Eir Maid",
    "Empress Doll",
    "Engineer",
    "Enlil",
    "Enyo",
    "Erin",
    "Erno",
    "Eros",
    "Eunice",
    "Excalibur",
    "Fel",
    "Fiona",
    "Flora",
    "Florid Pericallis",
    "Fortune Egg",
    "Frappe",
    "Fruit Candle",
    "Gabriel",
    "Gaia",
    "Gamigin",
    "Ganache",
    "Gem Christmas",
    "Gem Noir",
    "Gem Stolas",
    "Ginette",
    "Golgoroth",
    "Harariel",
    "Harnett",
    "Heaven's Gate",
    "High Elf",
    "High Priest",
    "Hina",
    "Holo",
    "Hresvelgr",
    "Iarn",
    "Ilmatar",
    "Ion",
    "Iris",
    "Iroha",
    "Ishtar",
    "Jodie",
    "Jodie Explorer",
    "Kathleen",
    "Kiki",
    "Kikurihime",
    "Kirsch",
    "Kokone",
    "Komainu Twins",
    "Konohanasakuya",
    "Lakshmi",
    "Lamoureux",
    "Lapfel",
    "Layla",
    "Legend Gambler",
    "Lemon",
    "Li Linfu",
    "Light Fairy",
    "Lightning Volt",
    "Lil' New Year",
    "Lirissa",
    "Lock Heart",
    "Luluka",
    "Luna",
    "Lynette",
    "Macaron",
    "Machina",
    "Maestra Luluka",
    "Manticore",
    "Melodic Mimi",
    "Metatron",
    "Metis",
    "Mia",
    "Michael",
    "Mikaity",
    "Mimi",
    "Mireia",
    "Mithras",
    "Morphium",
    "Morphium New Year",
    "Morta",
    "Ms. Kyoko",
    "Muffin",
    "Multiple Eye",
    "Muspell",
    "Mythic Knight",
    "Mythic Knight (Old)",
    "Narukami",
    "Nausicaa",
    "New Amath Haq",
    "Nicola",
    "Nike",
    "Niumri",
    "Noah",
    "Noel",
    "Nymph",
    "Olav",
    "One-Eyed Dragon",
    "Ono No Takamura",
    "Oruro",
    "Palella",
    "Pan",
    "Parentalia",
    "Parfait",
    "Parvati",
    "Pele",
    "Penemue",
    "Pericallis",
    "Pincho",
    "Ping",
    "Pirates Gun",
    "Polaris",
    "Pudding",
    "Qilin",
    "Quayle",
    "Quetzalcoatl",
    "Quraly",
    "Raphael",
    "Reinette",
    "Rem",
    "Rise & Shine",
    "Rookie Hatsune",
    "Roseria",
    "Rosetta",
    "Ruler Girl",
    "Sacrifice",
    "Saint",
    "Santa's Apprentice",
    "Schalk",
    "Schnee",
    "Sea Princess",
    "Shizuka",
    "Sky-High Effole",
    "Slipper Spirit",
    "Smalt",
    "Smokey",
    "Soell",
    "Soiree",
    "Spenta Mainyu",
    "Star Shower",
    "Stardust",
    "Sterix",
    "Sunray Suzu",
    "Super Chimry (Light)",
    "Suzu",
    "Talisman",
    "Tama-No-Oya",
    "Teatime",
    "Teiaiel",
    "Tensen Nyannyan",
    "Teresa",
    "Tetea",
    "Thelxinoe",
    "Thor",
    "Thviti",
    "Titania",
    "Uriel",
    "Ursula",
    "Ushas",
    "Vaccine",
    "Venus",
    "Verethragna",
    "Vesti",
    "Vidar",
    "Virtual Vandal",
    "Vitruvius",
    "Vulthoom",
    "Wandering Sanzo",
    "Warm Milk",
    "Weiss",
    "White Tiger",
    "White Xiong",
    "Will-o'-the-Wisp",
    "Windsurfer",
    "Xochiquetzal",
    "Zofia",
]

const SR_PASSION = [
    "4th Hammer",
    "Accordion",
    "Advent Fairy",
    "Ai",
    "Alchemist Ex",
    "Alice",
    "Alicia",
    "Alp",
    "Alviss",
    "Amaterasu",
    "Ame-No-Uzume",
    "Amphis",
    "Amy",
    "Angry Nehrin",
    "Anise",
    "Anna",
    "Apotheker",
    "Aries",
    "Aurora Captain Cook",
    "Bacchus",
    "Baku",
    "Banquet Leviatan",
    "Bear Hunter",
    "Beastia",
    "Beatty",
    "Birthday",
    "Black Magic Woman",
    "Bloody Mary",
    "Bobbin' Apple",
    "Bran",
    "Brim",
    "Cacao",
    "Cachalot",
    "Captain Cook",
    "Captain Kidd",
    "Carabine",
    "Catherine",
    "Cerberus",
    "Cerfbury",
    "Chamuel",
    "Chocolate Maker",
    "Christine",
    "Christmas Lum Lum",
    "Circe",
    "Coorie",
    "Cosmonaut",
    "Cthugha",
    "Cu Chulainn",
    "Cu Sith",
    "Cupid",
    "Curtana",
    "Cybele",
    "Dame Ridill",
    "Destroyer",
    "Diana (New)",
    "Dr. Mole",
    "Eir",
    "Eliza",
    "Elma",
    "Elsa",
    "Elune",
    "Empusa",
    "Enforcer",
    "Ensemble",
    "Estella",
    "Evergreen",
    "Evil Lady",
    "Filo",
    "Firecracker",
    "Foodie",
    "Fortuna",
    "Ghostly Anne",
    "Green Christmas",
    "Griffin",
    "Grimoire Of Curses",
    "Halloween Citrus",
    "Heartthrob",
    "Hestia",
    "Hiderigami",
    "Hot Spring Citrus",
    "Houri",
    "Ichthyo",
    "Ifrit",
    "Illumi",
    "Imoko",
    "Israfil",
    "Izumo No Okuni",
    "Jasmine",
    "Journalist",
    "Junior Director",
    "Juvie",
    "Kaho",
    "Killer Idol",
    "Kisaragi",
    "Kokkuri Fox",
    "Koko",
    "Kyklos",
    "Lady Garnet",
    "Lamp",
    "Leto",
    "Leviatan",
    "Lily",
    "Little Shion",
    "Livre",
    "Lofn",
    "Lolita Alchemist",
    "Lorayne",
    "Loveberry",
    "Lu",
    "Lucky Ten",
    "Madre",
    "Maid Izumi",
    "Maidryl",
    "Mars",
    "Master Alchemist",
    "Matador",
    "Mauve",
    "Mei Mei",
    "Midry",
    "Mika Live!",
    "Minette",
    "Mnemosyne",
    "Nami",
    "Nehrin",
    "Nezha",
    "Ninja Master",
    "Nona",
    "Nova",
    "Nova Shell",
    "Nuada",
    "Ogma",
    "Oinari",
    "Omikoshi",
    "Omoikane",
    "Orchestra",
    "Otanukisama",
    "Palladio",
    "Parade Princess",
    "Passion Fairy",
    "Patience",
    "Pheme",
    "Pianta",
    "Pigsy",
    "Poltergeist",
    "Precious Amy",
    "Princess",
    "Psyche",
    "Pyromaniac",
    "Queen Momo",
    "Queen of Amazons",
    "Ragnarok",
    "Rain Doll",
    "Reindeer Girl",
    "Renard",
    "Ridill",
    "Rokumonsen",
    "Ruilium",
    "Sacred Fire",
    "Salir",
    "Saya",
    "Scathach",
    "Scylla",
    "Securie",
    "Sephy Colden",
    "Sgt. Dynamite",
    "Shogi Master",
    "Shy Sally",
    "Sjofn",
    "Slider",
    "Sogia",
    "Sophie",
    "Soul Eater",
    "Sound Spirit",
    "Spider Web",
    "Sticker Freak",
    "Sulis",
    "Super Chimry (Passion)",
    "Swimsuit Muffin",
    "Thetis",
    "Tisiphone",
    "Tomato Juice",
    "Tomoe",
    "Tomoe Gozen",
    "Topo",
    "Tula",
    "Uranus",
    "Vermilion Bird",
    "Vesta",
    "Virago Ichthyo",
    "Volcanus",
    "Warning",
    "Whipper",
    "White Dragon",
    "Yosakoi",
    "Zenobia",
]

export default {
    Cool: SR_COOL,
    Dark: SR_DARK,
    Light: SR_LIGHT,
    Passion: SR_PASSION,
}